---
kind: ConfigMap
apiVersion: v1
metadata:
  name: slack-first
data:
  config.yaml: |
    supportChannelId: C01RY7X79R9
    onCall:
      schedule: weekly
      members:
        - qgzscsdqiaipryerya@twzhhq.com
        - xucosycqekvlwcexvi@upived.online
    github:
      issues:
        access:
          - tumido/slack-first
        labels: [question]
