---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - configmap.yaml

generators:
  - secret-generator.yaml

configMapGenerator:
  - name: slack-first
    behavior: merge
    files:
      - config.yaml
