name: Release

on:
  repository_dispatch:
    types: [trigger-release]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Update comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.client_payload.github.event.issue.number }}
          comment-id: ${{ github.event.client_payload.commentId }}
          body: |
            🎁 Publishing to Quay.io. New job started [here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: S2I Build
        uses: redhat-actions/s2i-build@v2
        with:
          path_context: "."
          builder_image: "registry.access.redhat.com/ubi8/nodejs-18"
          image: slack-first
          tags: ${{ github.event.client_payload.releaseVersion }} latest

      - name: Tag as latest
        run: docker tag slack-first:${{ github.event.client_payload.releaseVersion }} slack-first:latest

      - name: Push To Quay Action
        uses: redhat-actions/push-to-registry@v2
        with:
          image: slack-first
          tags: latest ${{ github.event.client_payload.releaseVersion }}
          registry: quay.io/tcoufal
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Update comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.client_payload.github.event.issue.number }}
          comment-id: ${{ github.event.client_payload.commentId }}
          body: |
            🎉 Released!
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Close Issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.client_payload.github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
